### ISSUE TITLE
Remove globals section

### ISSUE THREAD

**Issue by kristoforsalmin** [kraftvaerk/eslint-config-kraftvaerk#11]
Hi 😄 I think we need to remove [`globals` section](https://github.com/kraftvaerk/eslint-config-kraftvaerk/blob/master/index.js#L9-L14) from our config. It doesn't really make sense since we're using webpack now. If needed one could define `globals` on a per-project basis. What do you think? Thanks.

**Comment by mi2oon** [comment]
@racse1 Valid point as always 👍
