### ISSUE TITLE
Error 'key' is defined but never used - no-unused-vars

### ISSUE THREAD

**Issue by rammi987** [kraftvaerk/eslint-config-kraftvaerk#15]
```
const = [{AuctionName: 'test', InspectionStartDate: '000000T0000Z'}, {AuctionName: 'test', InspectionStartDate: '000000T0000Z'}];
        Object.entries(items).forEach(([key, val]) => { // eslint-disable-line
            html += `<li>
                    <h3>${val.AuctionName}</h3>
                    <time>Inspection: ${_.formatDate(val.InspectionStartDate)}' - '${_.formatDate(val.InspectionEndDate)}</time>
                    <time>Sales: ${_.formatDate(val.AuctionStartDate)}' - '${_.formatDate(val.AuctionEndDate)}</time>
                </li>`;
        });
```

This follow code above is valid in ES6, but the eslint complaning about unused.

**Comment by kristoforsalmin** [comment]
Hi @rammi987 ,

Just checked our ESLint config. The `no-unused-vars` rule comes from `eslint:recommended` preset and it has a [default value](https://eslint.org/docs/rules/no-unused-vars#options).

Back to your example, even if you really want to use `Object.entries()`, then why keep `key` anyway? Since `forEach` takes an array and then you destructing it, then `key` and `val` aren't function arguments, which means you can easily do this instead `Object.entries(items).forEach(([, val]) => { ... });`.

Does that solve your issue? 😄

**Comment by rammi987** [comment]
@racse1 Sure ([,val]) => does the work, but i dont like the [,val] syntax,
first i thouge that you was making a typo until i tried it

**Comment by kristoforsalmin** [comment]
@rammi987,

> but i dont like the [,val] syntax

Neither do I 😄 However, there's nothing we can do about it — it's been there for a long time.

As far as I can see, ESLint doesn't provide any specific options for addressing array destruction when used as an argument. Therefore, the only way to avoid linting is to disable rule altogether which I wouldn't like us to do, given that such cases are somewhat rare.

Lastly, you can either disable the rule on per-project basis or, as I mentioned before, use `Object.values()` instead.

@mi2oon thoughts? 😄

**Comment by mi2oon** [comment]
@rammi987 @racse1 I would agree to the `object.value` usage. However, if for some reason it's not usable I would also just disable the rule for the line or file or even project. But do limit disabling the rule unless highly necessary. As for the `[,val]` it perhaps looks a bit dirty but that's how it's specified. I've used it before like `[val1,,val3,val4]` 🙃

**Comment by kristoforsalmin** [comment]
I'm going to close the issue as it seems we kind of settled. @rammi987 feel free to reopen if you have anything to add.
