### ISSUE TITLE
Indentaion inside switch statement

### ISSUE THREAD

**Issue by kristoforsalmin** [kraftvaerk/eslint-config-kraftvaerk#3]
Hi 😃 

I've noticed that indentation inside `switch` statement isn't allowed. Is there any reason why? Thanks!

![`switch` statement](https://user-images.githubusercontent.com/4795426/39139194-e9aba9d4-4729-11e8-858c-e2e02b61d275.png)

**Comment by mi2oon** [comment]
@racse1 Nope, it was an issue with eslint as far as I remember. However, it seems like they might have [fixed](https://github.com/eslint/eslint/issues/1797) it. So we should probably update our code.

**Comment by kristoforsalmin** [comment]
Thanks, alright, I'll then update it alongside with the space before blocks rule 👍

**Comment by kristoforsalmin** [comment]
Wait for #10 before proceed.
