### ISSUE TITLE
Require space before blocks or not?

### ISSUE THREAD

**Issue by kristoforsalmin** [kraftvaerk/eslint-config-kraftvaerk#4]
Hi, let's discuss whether we need to require [space before blocks](https://eslint.org/docs/rules/space-before-blocks) (including arrows and keywords) or not? Currently we don't particularly care about that, but it'd be nice if we have a preference.

Personally, I always include a space before blocks as recommended by many other style guides out there 😃 

Thanks

**Comment by mi2oon** [comment]
@racse1 I thought we had a rule covering that one somewhere. However, I like you also use space. So lets just add it... I will let you do the honors :D

**Comment by kristoforsalmin** [comment]
Wait for #10 before proceed.
